// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ikUP3P48hH8DzzNm0dG6vnX4dfc5UVo',
    appId: '1:165125016765:web:85332f0c576cd38b013bd4',
    messagingSenderId: '165125016765',
    projectId: 'fitmirror-8a0b0',
    authDomain: 'fitmirror-8a0b0.firebaseapp.com',
    storageBucket: 'fitmirror-8a0b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNm3yE96OTOKlF1n7T5L3XTO8P1MrbAI',
    appId: '1:165125016765:android:4b88d919fdec0343013bd4',
    messagingSenderId: '165125016765',
    projectId: 'fitmirror-8a0b0',
    storageBucket: 'fitmirror-8a0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk21fEG6uLVCqAoXj-dBM4NgPGh1NU2mc',
    appId: '1:165125016765:ios:27ebd03d64462837013bd4',
    messagingSenderId: '165125016765',
    projectId: 'fitmirror-8a0b0',
    storageBucket: 'fitmirror-8a0b0.firebasestorage.app',
    iosBundleId: 'com.example.fitmirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk21fEG6uLVCqAoXj-dBM4NgPGh1NU2mc',
    appId: '1:165125016765:ios:27ebd03d64462837013bd4',
    messagingSenderId: '165125016765',
    projectId: 'fitmirror-8a0b0',
    storageBucket: 'fitmirror-8a0b0.firebasestorage.app',
    iosBundleId: 'com.example.fitmirror',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ikUP3P48hH8DzzNm0dG6vnX4dfc5UVo',
    appId: '1:165125016765:web:495226fa5f44df4d013bd4',
    messagingSenderId: '165125016765',
    projectId: 'fitmirror-8a0b0',
    authDomain: 'fitmirror-8a0b0.firebaseapp.com',
    storageBucket: 'fitmirror-8a0b0.firebasestorage.app',
  );
}
